from colorama import Fore,init
import os
from datetime import datetime

init(autoreset=True)


class ReportService:
    """Generate and save security analysis reports."""

    def __init__(self, reports_folder: str = "reports"):
        """Initialize the report service.

        Args:
            reports_folder (str): Folder where generated reports will be saved.
        """
        project_dir = os.path.dirname(os.path.dirname(__file__))
        self.reports_folder = os.path.join(project_dir, reports_folder)

        if not os.path.exists(self.reports_folder):
            os.makedirs(self.reports_folder)

    def generate_report(
        self,
        summary: dict,
        alerts: list,
        risk_score: int,
        threat_level: str,
        user_name: str
    ):
        """Generate and save a security analysis report.

        The report includes:
        - Log summary
        - Top IP addresses
        - Top event types
        - Detected alerts
        - Risk score
        - Threat level

        Args:
            summary (dict): Summary generated from log analysis.
            alerts (list): List of detected alerts.
            risk_score (int): Calculated risk score.
            threat_level (str): Calculated threat level.
            user_name (str): Name of the user generating the report.

        Returns:
            str: Full path to the generated report file.
        """
        current_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        file_name = f"security_report_{user_name}_{current_time}.txt"
        report_path = os.path.join(self.reports_folder, file_name)

        with open(report_path, "w", encoding="utf-8") as file:
            file.write("========== Security Analysis Report ==========\n\n")
            file.write(f"Generated By: {user_name}\n")
            file.write(f"Generated At: {current_time}\n\n")

            file.write(f"Total Logs: {summary['total_logs']}\n\n")

            file.write("Top IPs:\n")
            for ip, count in summary["top_ips"]:
                file.write(f"- {ip}: {count}\n")

            file.write("\nTop Events:\n")
            for event, count in summary["top_events"]:
                file.write(f"- {event}: {count}\n")

            file.write("\nDetected Alerts:\n")
            if alerts:
                for index, alert in enumerate(alerts, start=1):
                    file.write(f"{index}. {alert['type']}\n")
                    file.write(f"   {alert['message']}\n")
            else:
                file.write("No suspicious activity detected.\n")

            file.write("\nRisk Assessment:\n")
            file.write(f"Risk Score: {risk_score}\n")
            file.write(f"Threat Level: {threat_level}\n")

        return report_path