from colorama import Fore,init


init(autoreset=True)

class RiskEngine:
    """Calculate risk score and threat level based on detected alerts."""

    def __init__(self, alerts: list):
        """Initialize the risk engine.

        Args:
            alerts (list): List of detected alerts generated by detection rules.
        """
        self.alerts = alerts

    def calculate_score(self):
        """Calculate the total risk score based on alert types.

        Each alert type contributes a predefined score value. The final
        score is capped at 100.

        Returns:
            int: Calculated risk score (maximum 100).
        """
        score = 0

        for alert in self.alerts:
            if alert["type"] == "SQL Injection":
                score += 30

            elif alert["type"] == "Suspicious RDP Activity":
                score += 25

            elif alert["type"] == "Suspicious PowerShell Activity":
                score += 25

            elif alert["type"] == "Suspicious PowerShell Command":
                score += 40

            elif alert["type"] == "Suspicious File Download":
                score += 20

            elif alert["type"] == "Brute Force Attack":
                score += 35

        return min(score, 100)

    def get_threat_level(self):
        """Determine the threat level based on the calculated risk score.

        Threat levels are classified as:
        - Low
        - Medium
        - High
        - Critical

        Returns:
            str: Calculated threat level.
        """
        score = self.calculate_score()

        if score >= 70:
            return Fore.RED +"Critical"
        elif score >= 50:
            return Fore.RED +"High"
        elif score >= 25:
            return Fore.YELLOW +"Medium"
        else:
            return Fore.GREEN +"Low"